### ISSUE TITLE
Error message for cloning repository during setup

### ISSUE THREAD

**Issue by eegraves** [gge-ucd/R-DAVIS#19]
<img width="749" alt="ssh" src="https://user-images.githubusercontent.com/35232309/34755852-dfff014c-f57b-11e7-9373-7ce9507a943e.png">
<img width="726" alt="http" src="https://user-images.githubusercontent.com/35232309/34755853-e13b25fe-f57b-11e7-9a0a-57a6821625f0.png">

I ran into an issue (error messages shown in attached images, both for SSH and HHTP attempts) with my computer during setup and cloning of the repository. Ryan was able to manually fix the problem, and he will provide the solution that he found below. Thanks Ryan!

**Comment by ryanpeek** [comment]
Thanks @eegraves, I'm going to move this to our Discussion repository so that it's on record for the class!
