### ISSUE TITLE
automatic installation of R packages

### ISSUE THREAD

**Issue by mikoontz** [gge-ucd/R-DAVIS#41]
There are lots of required packages in order to build the website. I'm currently going through the process of building the site, seeing which package is not yet installed, installing that package, then building again. Is there an easy, automated way to do this?

**Comment by MCMaurer** [comment]
I'd like to try this out, how are you building the site locally? I've never tried doing it before.

**Comment by MCMaurer** [comment]
Working on this, starting by running `grep -r 'library(' R-DAVIS/` and finding all the package names, now I'm just trying to pull them all out

**Comment by mikoontz** [comment]
Oh, that's a good idea! Here's how to build:

1. Once you've pulled the latest website version to your machine (make sure it has Ryan's updated .RProj without the WebsitePath line), go to the "Build" tab in the "Environment/History/Git/Build" pane of RStudio.
1. Under "More" click "Clean all" to remove all derived files from the directory.
1. Then click "Build website" and all of the .Rmd and .yml etc. will be rendered into html in the docs folder and the site should build. You should be able to open the index.html file to view the site.

**Comment by ryanpeek** [comment]
I'm merging all patches now and will rebuild and push new updated version up shortly. We could add some initial list of packages which sits in the README (or associated file) that folks can check and use to see if it's installed, if not, then install?

**Comment by ryanpeek** [comment]
here's a list of packages I've pulled to add to the README (along with a few sentences describing how to build site locally). Can you all (@mikoontz @MCMaurer) take a look and see if you have any others I'm missing?

```tidyverse
ggplot2
tidyr
readr
dplyr
purrr
emojifont
viridis
mapdata
maps
measurements
gapminder
broom
gutenbergr
tidytext
patchwork
cowplot
hexbin
geosphere
ggmap
ggthemes
magrittr
leaflet
plotly
knitr```

**Comment by MCMaurer** [comment]
I had to install `emo` with `devtools::install_github("hadley/emo")` as well.

**Comment by ryanpeek** [comment]
yea I switched that out for emojifont since it does the same thing and doesn't require devtools...

**Comment by mikoontz** [comment]
@MCMaurer, how does @ryanpeek's list match with yours?

**Comment by MCMaurer** [comment]
After running `grep -horE 'library\(.*?\)' R-DAVIS/ | sed 's/library//g' | sed 's/[()]//g' | sort | uniq` I got this list:

```
"tidyverse"
'ggplot2'
broom
cowplot
dplyr
dplyr, warn.conflicts = F
emojifont, quietly = T
gapminder
geosphere
ggmap
ggplot2
ggthemes
gutenbergr
hexbin
knitr
leaflet
lubridate
lubridate, warn.conflicts = F
magrittr
mapdata
maps
measurements
patchwork
plotly
purrr
readr
tidyr
tidytext
tidyverse
viridis
```

Looks like it matches Ryan's!

**Comment by nistara** [comment]
Hey guys, thanks for this great resource for us non-ecology folks too! I'm trying to build the site locally as well and the above shell script somehow didn't work work me. Was able to get the packages with similar versions of it below:
```
grep -horE 'library\(.*?\)' . | sed 's/library//g; s/[()]//g; s/"//g' | sed "s/\'//g" | grep -Eo '^\w+' | sort | uniq 
grep -horE 'library\(.*?\)' . | sed 's/library//g; s/[()]//g; s/"//g' | grep -Eo '^\w+' | sort | uniq
```
