### ISSUE TITLE
polygon edge not found error in lessons

### ISSUE THREAD

**Issue by mikoontz** [gge-ucd/R-DAVIS#51]
So far, I'm seeing this error in the CO2 pipeline lesson and in the text mining lesson. Could be a computer restart issue (https://github.com/ricardo-bion/ggradar/issues/3). I'll report back.

**Comment by MCMaurer** [comment]
I can't even build the site because it won't establish a connection with `http://cdiac.ornl.gov/ftp/trends/co2/vostok.icecore.co2` in that lesson. Any thoughts?

**Comment by mikoontz** [comment]
I had some trouble with a few of the links in that lesson. I set a few of the chunk's eval= argument to FALSE.

**Comment by ryanpeek** [comment]
Yup...I fixed the data links...turns out that data has been obfuscated under a bunch of other stuff. I took a copy of the raw data and put it locally in our repo, then changed links to point to it so the lesson will now run. Should work now...(at least it does on mine using a local build)

**Comment by ryanpeek** [comment]
also I've had that polygon edge error on and off, and usually it can be eliminated using session restart or just re-running the plotting code. I'm not sure why it happens, sometimes might relate to size of plotting window in RStudio? It used to happen fairly regularly with sf plots or large ggplots.

**Comment by mikoontz** [comment]
thanks for getting a local copy of those data. Yes, the 'polygon edge not found' error has always been intermittent (and frustrating!) in other work. I concur we shouldn't worry about it here.
