### ISSUE TITLE
only Rmd in root project directory will be rendered on a web Build

### ISSUE THREAD

**Issue by ryanpeek** [gge-ucd/R-DAVIS#94]
Hi @MCMaurer @MarthaWohlfeil, after poking around in the rmarkdown website documentation, it looks like only Rmd's in the actual root project directory will be rendered when building the site. Anything with a preceding "`_`" *won't* be rendered, along with other stuff (like files starting with a period, etc). So, if you want Rmd files to be included and built with the site, then I think we need to keep those lessons (archived or not) in the root folder. Unfortunately this is one of the limitations of using an Rmarkdown/Rstudio based website, it's pretty simplistic (which is nice) but also has limits to keeping things organized via the folder approach. 

I'll submit a pull request in a bit with a possible fix...there are two options:

1. Appending the year to lessons, and then only moving the ones out from the archive folder that you want/need to build (i.e., most of the stuff in the **Resources>Bonus Lessons** section).

2.  Knitting just the `.Rmd`'s you need to `html` directly (need to add some stuff to yaml header to format similarly), and then referencing that file in the website build link just as we normally do. This may bypass the issue, but these `html` pages won't have the same R-DAVIS header/menu/ formatting associated with the website because they are standalone pages. 

Up to you all how you want to proceed, but thought I'd pass this along!

**Comment by MCMaurer** [comment]
Thanks so much for looking into this! We accepted that PR, I think adding the year to the lessons is definitely the way to go. Still keeps things clean and organized in the archive folder.
